use toolkit_core::config::Config;
use async_openai::{
    Client,
    config::OpenAIConfig,
    types::{
        ChatCompletionRequestSystemMessageArgs,
        ChatCompletionRequestUserMessageArgs,
        CreateChatCompletionRequestArgs,
    },
};

/// Split a diff string into chunks capped at `max_words` words per chunk.
pub fn split_diff_into_chunks(diff: &str, max_words: usize) -> Vec<String> {
    if diff.trim().is_empty() {
        return vec![];
    }
    let lines: Vec<&str> = diff.lines().collect();
    let mut chunks = vec![];
    let mut current: Vec<&str> = vec![];
    let mut count = 0usize;

    for line in lines {
        let words = line.split_whitespace().count();
        if count + words > max_words && !current.is_empty() {
            chunks.push(current.join("\n"));
            current.clear();
            count = 0;
        }
        current.push(line);
        count += words;
    }
    if !current.is_empty() {
        chunks.push(current.join("\n"));
    }
    chunks
}

/// Send each diff chunk to vLLM and return concatenated Markdown review.
pub async fn review_diff(diff: &str, model: &str, cfg: &Config) -> Option<String> {
    if diff.trim().is_empty() {
        return None;
    }

    let client = Client::with_config(
        OpenAIConfig::new()
            .with_api_base(&cfg.vllm_base_url)
            .with_api_key("none"),
    );

    let chunks = split_diff_into_chunks(diff, 2000);
    let mut reviews = vec![];

    for (i, chunk) in chunks.iter().enumerate() {
        println!("Reviewing chunk {}/{}...", i + 1, chunks.len());
        let req = match CreateChatCompletionRequestArgs::default()
            .model(model)
            .messages([
                ChatCompletionRequestSystemMessageArgs::default()
                    .content("You are a code reviewer. Be brief, practical, and output final answer only.")
                    .build()
                    .ok()?
                    .into(),
                ChatCompletionRequestUserMessageArgs::default()
                    .content(format!(
                        "Review this code diff. Return only Markdown sections: Issues, Improvements, Positives.\n\n```diff\n{chunk}\n```"
                    ))
                    .build()
                    .ok()?
                    .into(),
            ])
            .max_tokens(350u32)
            .temperature(0.1_f32)
            .build()
        {
            Ok(r) => r,
            Err(e) => {
                eprintln!("Warning: Failed to build request for chunk {}: {e}", i + 1);
                continue;
            }
        };

        match client.chat().create(req).await {
            Ok(resp) => {
                if let Some(text) = resp
                    .choices
                    .into_iter()
                    .next()
                    .and_then(|c| c.message.content)
                    .filter(|t| !t.trim().is_empty())
                {
                    reviews.push(text);
                } else {
                    eprintln!("Warning: Chunk {}: empty response from model", i + 1);
                    reviews.push(format!("Chunk {}: empty model response", i + 1));
                }
            }
            Err(e) => {
                eprintln!("Warning: Chunk {} error: {e}", i + 1);
                reviews.push(format!("Chunk {}: error during analysis", i + 1));
            }
        }
    }

    if reviews.is_empty() { None } else { Some(reviews.join("\n\n---\n\n")) }
}

/// Post the review text as a PR comment via the GitHub REST API.
pub async fn post_pr_comment(
    review: &str,
    repo: &str,
    pr_number: u64,
    token: &str,
) -> bool {
    const MAX_LEN: usize = 60_000;
    let source_label = std::env::var("REVIEW_ENGINE_LABEL")
        .unwrap_or_else(|_| "self-hosted AI reviewer".to_string());
    let mut body = format!(
        "## AI Code Review\n\n{review}\n\n---\n*This review was generated by {source_label}.*"
    );
    if body.len() > MAX_LEN {
        body.truncate(MAX_LEN - 50);
        body.push_str("\n\n[Truncated due to GitHub comment size limit]");
    }

    let client = reqwest::Client::new();
    let url = format!(
        "https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    );
    client
        .post(&url)
        .header("Authorization", format!("token {token}"))
        .header("User-Agent", "code-review-cli")
        .json(&serde_json::json!({ "body": body }))
        .send()
        .await
        .map(|r| r.status().is_success())
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn chunks_split_on_word_count() {
        // Build a diff with many lines so word count exceeds max_words=2000
        let big = (0..5000).map(|i| format!("+ word{i}")).collect::<Vec<_>>().join("\n");
        let chunks = split_diff_into_chunks(&big, 2000);
        assert!(chunks.len() > 1);
    }

    #[test]
    fn empty_diff_yields_no_chunks() {
        assert!(split_diff_into_chunks("", 2000).is_empty());
        assert!(split_diff_into_chunks("   \n  ", 2000).is_empty());
    }

    #[test]
    fn small_diff_is_single_chunk() {
        let diff = "- old line\n+ new line\n";
        let chunks = split_diff_into_chunks(diff, 2000);
        assert_eq!(chunks.len(), 1);
        assert_eq!(chunks[0], diff.trim_end_matches('\n'));
    }
}
